---
- hosts: aws_ec2
  become: yes
  remote_user: ubuntu
  connection: ssh
  vars:
    ansible_ssh_private_key_file: "/root/ansible/pem.pem"
    ansible_ssh_user: "ubuntu"

  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: install git
      apt:
        name: git
        state: present

    - name: remove default path
      file:
        path: /var/www/
        state: absent

    - name: deploy code
      git:
        repo: "https://github.com/devops0014/staticsite-docker.git"
        dest: /var/www/
        update: yes
        version: master

    - name: start apache2
      service:
        name: apache2
        state: started
